### ISSUE TITLE
I would use hipe llvm ;)

### ISSUE THREAD

**Issue by olafura** [jamen/brewery#1]
https://github.com/erlang/otp/tree/master/lib/hipe/llvm

**Comment by jamen** [comment]
Thanks.  I've looked at that before.

**Comment by jamen** [comment]
Any idea how I would access those APIs? I've tried `:hipe`/`:hipe_llvm` in Elixir.  Would I need to include the source in my project?

**Comment by jamen** [comment]
I've been learning!  Thanks.
